# Generated by Django 5.1.4 on 2025-01-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_phone_number_contactform_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='referer_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='submitted_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
