# Generated by Django 5.1.4 on 2025-02-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactform_referer_url_contactform_submitted_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
