# Generated by Django 5.1.4 on 2024-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_chooses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chooses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='chooses/')),
                ('description', models.TextField()),
            ],
        ),
    ]
