# Generated by Django 5.1.4 on 2024-12-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_chooses_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Differentiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DifferentiatorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='differtiator_entries/')),
                ('Differentiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='home.differentiator')),
            ],
        ),
    ]
