# Generated by Django 5.1.4 on 2024-12-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_title_differentiatorentry_differentiator_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='differentiatorentry',
            name='Differentiator',
        ),
        migrations.AlterField(
            model_name='differentiatorentry',
            name='image',
            field=models.ImageField(upload_to='entry_images/'),
        ),
        migrations.AddField(
            model_name='differentiatorentry',
            name='differentiator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.differentiator'),
            preserve_default=False,
        ),
    ]
