# Generated by Django 5.1.4 on 2024-12-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_title_industryentry_industries_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industryentry',
            old_name='industries_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='industryentry',
            old_name='industries_title',
            new_name='title',
        ),
    ]
