# Generated by Django 5.1.4 on 2024-12-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
