# Generated by Django 5.1.4 on 2024-12-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='blog_slug',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
