# Generated by Django 5.1.4 on 2024-12-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0002_remove_footer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
