# Generated by Django 5.1.4 on 2024-12-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_galleryimage_galleryvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
