# Generated by Django 5.1.4 on 2024-12-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='banner_img',
            new_name='image',
        ),
    ]
