# Generated by Django 5.1.4 on 2024-12-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('url', models.URLField()),
                ('position_top', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position_left', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
