# Generated by Django 5.1.4 on 2024-12-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_networkbanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkbanner',
            old_name='first_list',
            new_name='lists',
        ),
        migrations.RemoveField(
            model_name='networkbanner',
            name='second_list',
        ),
    ]
