# Generated by Django 5.1.4 on 2024-12-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_first_list_networkbanner_lists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkbanner',
            name='title_highlight',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
