# Generated by Django 5.1.4 on 2024-12-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_networkbanner_title_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
