# Generated by Django 5.1.4 on 2024-12-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_network_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
