# Generated by Django 5.1.4 on 2024-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_network_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
