# Generated by Django 5.1.4 on 2024-12-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_network_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='network',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='network',
            name='email',
        ),
        migrations.RemoveField(
            model_name='network',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='network',
            name='location',
        ),
        migrations.RemoveField(
            model_name='network',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='network',
            name='position',
        ),
    ]
