# Generated by Django 5.1.4 on 2024-12-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_network_company_name_network_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='position',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
