# Generated by Django 5.1.4 on 2024-12-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_network_address_alter_network_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='network',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
