# Generated by Django 5.1.4 on 2025-01-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careersform',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='careersform',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='careers_files/'),
        ),
        migrations.AddField(
            model_name='careersform',
            name='referer_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='careersform',
            name='submitted_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
