# Generated by Django 5.1.4 on 2025-02-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_delete_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('referer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('submitted_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
