# Generated by Django 5.1.4 on 2024-12-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='link_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
