# Generated by Django 5.1.4 on 2024-12-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rename_servicesbanner_servicestitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
