# Generated by Django 5.1.4 on 2024-12-31 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_subservicescategory_subservicescategoryentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subservicescategory',
            old_name='count',
            new_name='length',
        ),
    ]
