# Generated by Django 5.1.4 on 2024-12-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_specializedservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializedServiceBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='services/')),
            ],
        ),
    ]
