# Generated by Django 5.1.4 on 2024-12-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_specializedservicebanner_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specializedservicebanner',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
