# Generated by Django 5.1.4 on 2025-01-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_remove_specializedservicebanner_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservicescategoryentry',
            name='category',
        ),
        migrations.DeleteModel(
            name='SubServicesCategory',
        ),
        migrations.DeleteModel(
            name='SubServicesCategoryEntry',
        ),
    ]
