# Generated by Django 5.1.4 on 2025-01-07 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_subcategory_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='subcategory_cards/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_cards', to='services.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
