# Generated by Django 5.1.4 on 2025-01-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='text_color',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
