# Generated by Django 5.1.4 on 2025-01-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_alter_subcategory_enable_fill_empty_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializedservice',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
