# Generated by Django 5.1.4 on 2025-01-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_specializedservice_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specializedservice',
            name='link_url',
        ),
    ]
