# Generated by Django 5.1.4 on 2024-12-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_link_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
