# Generated by Django 5.1.4 on 2024-12-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicesbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='services/'),
        ),
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subservice_title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='services/')),
                ('title', models.CharField(max_length=500)),
                ('sub_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.services')),
            ],
        ),
    ]
