# Generated by Django 5.1.4 on 2024-12-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_subservices_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='banner_image',
            field=models.ImageField(default=1, upload_to='services/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='content_paragraphs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
