# Generated by Django 5.1.4 on 2024-12-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_count_subservicescategory_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservicescategory',
            name='length',
            field=models.CharField(max_length=200),
        ),
    ]
