# Generated by Django 5.1.4 on 2025-01-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_services_content_paragraphs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
