# Generated by Django 5.1.4 on 2025-01-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_services_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specializedservicebanner',
            name='link_url',
        ),
    ]
