# Generated by Django 5.1.4 on 2025-01-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_subcategory_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='enable_fill_empty_cards',
            field=models.BooleanField(default=False),
        ),
    ]
