# Generated by Django 5.1.4 on 2025-01-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_specializedservice_dedicated_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specializedservice',
            name='link_url',
        ),
    ]
