# Generated by Django 5.1.4 on 2024-12-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chooses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='decription',
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
