# Generated by Django 5.1.4 on 2024-12-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_banner_decription_banner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.CharField(max_length=255),
        ),
    ]
