# Generated by Django 5.1.4 on 2024-12-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_differentiator_differentiatorentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='differentiator',
            name='subtitle',
            field=models.CharField(max_length=2000),
        ),
    ]
