# Generated by Django 5.1.4 on 2024-12-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_differentiator_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='differentiatorentry',
            old_name='title',
            new_name='differentiator_title',
        ),
    ]
