# Generated by Django 5.1.4 on 2024-12-17 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_differentiatorentry_differentiator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='differentiatorentry',
            name='differentiator',
        ),
        migrations.AlterField(
            model_name='differentiatorentry',
            name='image',
            field=models.ImageField(upload_to='differtiator_entries/'),
        ),
        migrations.AddField(
            model_name='differentiatorentry',
            name='Differentiator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='home.differentiator'),
            preserve_default=False,
        ),
    ]
