# Generated by Django 5.1.4 on 2024-12-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_differentiatorentry_differentiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='differentiatorentry',
            name='image',
            field=models.ImageField(upload_to='differentiator_entries/'),
        ),
    ]
