# Generated by Django 5.1.4 on 2024-12-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
