# Generated by Django 5.1.4 on 2024-12-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='logo',
        ),
    ]
