# Generated by Django 5.1.4 on 2024-12-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_banner_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chooses',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
