# Generated by Django 5.1.4 on 2024-12-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_differentiatorentry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='differentiatorentry',
            name='Differentiator',
        ),
        migrations.DeleteModel(
            name='Differentiator',
        ),
        migrations.DeleteModel(
            name='DifferentiatorEntry',
        ),
    ]
