# Generated by Django 5.1.4 on 2024-12-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_differentiatorentry_differentiator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Differentiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DifferentiatorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='differentiators/')),
                ('differentiator_title', models.CharField(max_length=255)),
            ],
        ),
    ]
