# Generated by Django 5.1.4 on 2024-12-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_industries_description_industryentry_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryentry',
            name='path_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
