# Generated by Django 5.1.4 on 2025-02-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('position_top', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('position_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_highlight', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('highlights', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('lists', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
