# Generated by Django 5.1.4 on 2024-12-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_ourstoryentry_description_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourstoryentry',
            name='description_first',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='ourstoryentry',
            name='description_second',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='ourstoryentry',
            name='description_third',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
