# Generated by Django 5.1.4 on 2024-12-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_ourstoryentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurStoryEntry',
        ),
        migrations.AddField(
            model_name='ourstory',
            name='description_first',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourstory',
            name='description_second',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourstory',
            name='description_third',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourstory',
            name='image',
            field=models.ImageField(default=1, upload_to='story/'),
            preserve_default=False,
        ),
    ]
