# Generated by Django 5.1.4 on 2024-12-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_remove_missionentry_mission_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionentry',
            name='image',
            field=models.ImageField(upload_to='mission/'),
        ),
    ]
