# Generated by Django 5.1.4 on 2024-12-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_galleryimage_gallery_delete_galleryvideo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='GalleryBanner',
        ),
    ]
