# Generated by Django 5.1.4 on 2024-12-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_gallery_galleryimage_galleryvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryvideo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
