# Generated by Django 5.1.4 on 2024-12-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_gallery_main_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryvideo',
            name='thumbnail',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
