# Generated by Django 5.1.4 on 2024-12-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_galleryvideo_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='main_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
