# Generated by Django 5.1.4 on 2024-12-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourstoryentry',
            old_name='description',
            new_name='description_first',
        ),
        migrations.AddField(
            model_name='ourstoryentry',
            name='description_second',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourstoryentry',
            name='description_third',
            field=models.TextField(blank=True, null=True),
        ),
    ]
