# Generated by Django 5.1.4 on 2024-12-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_ourstoryentry_description_first_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurStoryEntry',
        ),
    ]
