# Generated by Django 5.1.4 on 2024-12-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_delete_ourstoryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurStoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='story/')),
                ('description_first', models.TextField()),
                ('description_second', models.TextField()),
                ('description_third', models.TextField()),
            ],
        ),
    ]
