# Generated by Django 5.1.4 on 2024-12-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_delete_ourstoryentry_ourstory_description_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ourteamentry',
            name='image',
        ),
    ]
