# Generated by Django 5.1.4 on 2024-12-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_remove_ourteam_description_remove_ourteamentry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionentry',
            name='mission_text',
        ),
        migrations.RemoveField(
            model_name='missionentry',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='missionentry',
            name='vision',
        ),
        migrations.AddField(
            model_name='missionentry',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionentry',
            name='image',
            field=models.ImageField(default=1, upload_to='story/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionentry',
            name='title',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
