# Generated by Django 5.1.4 on 2025-01-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_rename_phone_number_careersform_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersform',
            name='file',
            field=models.FileField(default=1, upload_to='careers_files/'),
            preserve_default=False,
        ),
    ]
