# Generated by Django 5.1.4 on 2024-12-27 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_services_image_subservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservices',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subservices',
            name='sub_services',
        ),
        migrations.RemoveField(
            model_name='subservices',
            name='title',
        ),
        migrations.AddField(
            model_name='subservices',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='services.services'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubServicesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/')),
                ('title', models.CharField(max_length=500)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services_categories', to='services.services')),
            ],
        ),
    ]
