# Generated by Django 5.1.4 on 2024-12-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_services_banner_image_services_content_paragraphs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesBanner',
            new_name='ServicesTitle',
        ),
        migrations.RemoveField(
            model_name='subservicescategory',
            name='service',
        ),
        migrations.DeleteModel(
            name='SubServices',
        ),
        migrations.DeleteModel(
            name='SubServicesCategory',
        ),
    ]
