# Generated by Django 5.1.4 on 2024-12-30 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_services_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServicesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=500)),
                ('fill_space', models.BooleanField()),
                ('text_color', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='services.services')),
            ],
        ),
        migrations.CreateModel(
            name='SubServicesCategoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/')),
                ('title', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='services.subservicescategory')),
            ],
        ),
    ]
