# Generated by Django 5.1.4 on 2024-12-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_specializedservicebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializedservicebanner',
            name='link_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
