# Generated by Django 5.1.4 on 2025-01-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_specializedservicebanner_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='content_paragraphs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
