# Generated by Django 5.1.4 on 2025-01-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_card_delete_subcategorycard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='cards/'),
        ),
    ]
