# Generated by Django 5.1.4 on 2025-01-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_subcategory_enable_fill_empty_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='enable_fill_empty_cards',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
