# Generated by Django 5.1.4 on 2025-01-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_remove_specializedservice_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializedservice',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
