# Generated by Django 5.1.4 on 2025-01-09 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_specializedservice_link_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_color', models.CharField(default='#212529', max_length=7)),
                ('enable_fill_empty_cards', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='services.specializedservice')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='services.specializedcategory')),
            ],
        ),
    ]
