# Generated by Django 5.1.4 on 2024-12-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_blogentry_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogbanner',
            name='blog_url',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
