# Generated by Django 5.1.4 on 2024-12-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_blogbanner_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blog_slug',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='blog_title',
            field=models.CharField(max_length=2000),
        ),
    ]
