# Generated by Django 5.1.4 on 2024-12-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_blogbanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogbanner',
            name='title_highlights',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
