# Generated by Django 5.1.4 on 2024-12-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_blogentry_additional_content_blogentry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='additional_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
